### ISSUE TITLE
Sprint 1 - Leo's Goals: CSS styling (box model, classes, ids, organization), GitHub (clarification on pull requests, code review, commit authorization)

### ISSUE THREAD

**Issue by lagerasimov17** [CNSabers/bscs2016#12]
- Finish HTML file 
- Begin CSS for own HTML file or multiple HTML files
- Learn about box model, classes, ids, general organization of styling
- Ask questions about HTML + CSS to improve understanding
- Clarify logistics on GitHub (pull requests, code review, commit authorization)

**Comment by shickey** [comment]
These sound like some solid goals, Leo. Specifically, it looks like you're interested in working on your software skills this week. Now let's get specific about CSS. One thing is particular that I'm going to encourage everyone to look into is what is called the CSS box model. It would be a good goal for you this week to be able to explain what that is and how to use it to apply some basic layout to your HTML document. Second, it would be good to understand what a class is and what an id is in CSS and how to use them to help style your HTML.

Also (and I'll say this to everyone), go ahead and update the title of this issue to reflect what your goals are rather than the generic "Leo's Goals". This is so that we can quickly see what _everyone's_ working on by clicking on the issues tab!

Let me know if you have more questions!

**Comment by lagerasimov17** [comment]
- HTML file: https://github.com/CNSabers/bscs2016/blob/9443a190f0b602cce5e093c275f19c4859aae5d5/choose_your_quiz.html
- CSS file:
  https://github.com/CNSabers/bscs2016/blob/9443a190f0b602cce5e093c275f19c4859aae5d5/choose_your_quiz.css

**Comment by shickey** [comment]
Nice job, Leo. Your code is looking good. How are you feeling about the box model and GitHub at this point (since those were specific goals of yours)?

**Comment by lagerasimov17** [comment]
Well, those are 2 things that I'm still working on understanding. GitHub is still proving to be difficult at times to comprehend, especially the organization. Hopefully I'll get it down with time. I also need to learn more about the box model in CSS, which I've learned to some extent while working on my primitive CSS modeling for my web page.
